environment:
- develop
- staging
- production

application_setting:
  ownerEmail: owner@personal.com
  cloudProvider:
  - kubernetes

pipeline_setting:
  default:
    artifactAccount: artifactoryAccount
    gitOwner: personal
    helmRepository: https://myhelm.repo.com/repository
    maintainer: maintainer
    namespace: default
    notifyEmailAddr: alert@personal.com
    spinnakerUri: https://spinnaker.personal.com
    kubeVersion: 1.16.9
  environment:
    develop:
      branch: master
      provider: develop
      releaseName: develop-release
      triggerEnabled: "true"
      valueFile: values.develop.yaml
      kubeVersion: 1.18.8
    staging:
      branch: tags
      provider: staging
      releaseName: staging-release
      triggerEnabled: "true"
      valueFile: values.staging.yaml
    production:
      branch: tags
      provider: production
      releaseName: production-release
      triggerEnabled: "false"
      valueFile: values.production.yaml
  application:
    app1:
      releaseName: app1-release
    app1.env:
      valuesOverrides:
        'rabbitmq.podAnnotations.vault\\.security\\.banzaicloud\\.io/vault-path': my-vault-path
    app2.develop:
      releaseName: app2-release
